controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Arm
arm_controller:
  ros__parameters:
    joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - grip_1_joint
    - grip_2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity